version: 6.0.{build}
branches:
  only:
  - master
  - development  
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
configuration: Release
environment:
  NUGET_API_KEY:
    secure: YPGdPLnY9FEYDZz3zZFV/+BKreynP4W2/DoURr0XlBjS8eLkkSypvEkI0BQSfRur
build: off    
build_script:
- ps: >-
    if ($env:APPVEYOR_REPO_BRANCH -ieq "development") {
      dotnet pack -c "Release" /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION --version-suffix "-beta"
    } else {
      dotnet pack -c "Release" /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION 
    }
    dotnet nuget push *.nupkg -k $env:NUGET_API_KEY
test: off